// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohmzyutudagjfuxailcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obXp5dXR1ZGFnamZ1eGFpbGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Nzg5NDEsImV4cCI6MjA3NDI1NDk0MX0.vHBaKfO_kzHv4YkO3yggl-Rx8WrO0Pcn21j16jS4S34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});